# Generated by Django 4.2.3 on 2023-07-25 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('cargo_image', models.ImageField(blank=True, null=True, upload_to='cargo_images/')),
                ('contact_number', models.CharField(default='359', max_length=12)),
                ('start_location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('total_km', models.IntegerField()),
                ('weight', models.CharField(choices=[('1.4', '1.4'), ('10', '10'), ('24', '24')], max_length=3)),
                ('cargo_type', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('To storage ', 'To storage '), ('Lost', 'Lost'), ('Cancelled', 'Cancelled')], max_length=11)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
