# Generated by Django 4.2.3 on 2023-07-24 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField()),
                ('start_location', models.CharField()),
                ('destination', models.CharField(max_length=200)),
                ('total_km', models.IntegerField()),
                ('weight', models.CharField(choices=[('1.4', '1.4'), ('10', '10'), ('24', '24')], max_length=3)),
                ('cargo_type', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('To storage ', 'To storage '), ('Lost', 'Lost'), ('Cancelled', 'Cancelled')], max_length=11)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
