# Generated by Django 4.2.3 on 2023-07-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_alter_cargo_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='status',
        ),
    ]
