# Generated by Django 4.2.3 on 2023-07-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_remove_cargo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='start_location',
        ),
    ]
