# Generated by Django 4.2.3 on 2023-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_remove_cargo_start_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
