# Generated by Django 4.2.3 on 2023-07-26 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guest_service', '0002_alter_guestserviceformsubmission_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestserviceformsubmission',
            name='date_asked',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
