# Generated by Django 4.2.3 on 2023-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_age_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Vehicle Owner', 'Vehicle Owner'), ('Cargo Owner', 'Cargo Owner'), ('Warehouse Owner', 'Warehouse Owner')], default='Cargo Owner', max_length=15),
        ),
    ]
