# Generated by Django 4.2.3 on 2023-07-28 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Tank truck', 'Tank truck'), ('Flatbed truck', 'Flatbed truck'), ('Refrigerator truck', 'Refrigerator truck'), ('Light truck', 'Light truck'), ('Car Carrier Trailer', 'Car Carrier Trailer'), ('Garbage truck', 'Garbage truck'), ('Mail truck', 'Mail truck')], max_length=19)),
                ('max_weight', models.CharField(choices=[('1.4', '1.4'), ('10', '10'), ('24', '24')], max_length=3)),
                ('current_location', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('waiting for delivery', 'waiting for delivery'), ('waiting for load', 'waiting for load'), ('on a break', 'on a break'), ('in process', 'in process')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('contact_number', models.CharField(default='+359', max_length=13)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
