# Generated by Django 4.2.3 on 2023-08-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='max_weight',
            field=models.CharField(choices=[('Up to 1.4 tons', 'Up to 1.4 tons'), ('Up to 10 tons', 'Up to 10 tons'), ('Up to 24 tons', 'Up to 24 tons')], max_length=14),
        ),
    ]
