# Generated by Django 4.2.3 on 2023-08-06 09:26

import LogiSolutions.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_max_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='contact_number',
            field=models.CharField(default='+359', max_length=13, validators=[LogiSolutions.core.validators.validate_phone_number]),
        ),
    ]
