# Generated by Django 4.2.3 on 2023-07-24 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('square_meters_capacity', models.PositiveIntegerField()),
                ('contact_person', models.CharField(max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
