# Generated by Django 4.2.3 on 2023-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
